spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: employee-api
          uri: http://localhost:9090
          predicates:
            - Path=/employee/**
        - id: payroll-api
          uri: http://localhost:9010
          predicates:
            - Path=/payroll/**
        - id: insurance-api
          uri: http://localhost:9020
          predicates:
            - Path=/insurance/**
server:
  port: 8080